version: '3.2'

services:
  dnsmasq:
    build: dnsmsaq-wiiu
    restart: always
    privileged: true
    network_mode: "host"
  nginx:
    image: nginx:latest
    restart: always
    volumes:
      - /root/containers/wiiu/nginx/nginx.conf:/etc/nginx/nginx.conf
      - /root/containers/wiiu/nginx/exploit:/etc/nginx/html/exploit
    network_mode: host

